repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: flake8
        args:
            - "--max-line-length=88"
            - "--max-complexity=18"
            - "--select=B,C,E,F,W,T4,B9"
            - "--ignore=E203,E266,E501,W503,F403,F401,E402,F811,B950"
            # these are errors that will be ignored by flake8
            # check out their meaning here
            # https://flake8.pycqa.org/en/latest/user/error-codes.html
        additional_dependencies: [
            'flake8-docstrings',
            "flake8-bugbear",
            "pep8-naming"
        ]
        exclude: pkg
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
        args:
            - --line-length=88

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
    -   id: bandit
        args: [-v, -n 3, -lll, --recursive, .]
